Repository ucsb-cs156-w22/team04-w22-7pm-courses, pull requests merged in 2022-03, with the labels that each got.

#20 Implemented UCSBSubjectsService and Tests for the 'get()' function
  .env.SAMPLE
  src/main/java/edu/ucsb/cs156/example/controllers/UCSBSubjectsController.java
  src/main/java/edu/ucsb/cs156/example/services/UCSBSubjectsService.java
  src/main/resources/application.properties
  src/test/java/edu/ucsb/cs156/example/services/UCSBSubjectsServiceTests.java
Labels: w22-7pm-1

#21 created placeholder UCSBSubjects table (frontend)
  .gitignore
  frontend/src/App.js
  frontend/src/fixtures/loadsubjectsFixtures.js
  frontend/src/main/components/LoadSubjects/LoadSubjectsTable.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/LoadSubjectsPage.js
  frontend/src/stories/pages/HomePage/LoadSubjectsPage.stories.js
  frontend/src/tests/components/LoadSubjects/LoadSubjectsTable.test.js
  frontend/src/tests/pages/LoadSubjectsPage.test.js
  src/main/java/edu/ucsb/cs156/example/controllers/UCSBSubjectsController.java
  src/test/java/edu/ucsb/cs156/example/controllers/UCSBSubjectsControllerTests.java
Labels: w22-7pm-2, Merge-Candidate

#22 Added the Button and LevelDropdown Components as well as appropriate Test Coverage
  frontend/src/main/components/Level/LevelDropdown.js
  frontend/src/main/components/SubmitButton/SubmitButton.js
  frontend/src/stories/components/Level/LevelDropdown.stories.js
  frontend/src/stories/components/SubmitButton/SubmitButton.stories.js
  frontend/src/tests/components/Level/LevelDropdown.test.js
  frontend/src/tests/components/SubmitButton/SubmitButton.test.js
Labels: w22-7pm-1, attn-respond to CR

#23 Added backend CRUD endpoints for Personal Schedules
  src/main/java/edu/ucsb/cs156/example/controllers/PersonalSchedulesController.java
  src/main/java/edu/ucsb/cs156/example/entities/PersonalSchedule.java
  src/main/java/edu/ucsb/cs156/example/repositories/PersonalScheduleRepository.java
  src/test/java/edu/ucsb/cs156/example/controllers/PersonalSchedulesControllerTests.java
Labels: w22-7pm-2, 20

#29 Load Subjects Button
  .env.SAMPLE
  frontend/src/main/pages/LoadSubjectsPage.js
  frontend/src/stories/components/LoadSubjects/LoadSubjectsTable.stories.js
  frontend/src/stories/pages/HomePage/LoadSubjectsPage.stories.js
  frontend/src/tests/pages/LoadSubjectsPage.test.js
Labels: w22-7pm-2, Merge-Candidate

#30 -WL Implemented a UCSBSubjects Table for the frontend
  frontend/src/fixtures/ucsbSubjectsFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/UCSBSubjects/UCSBSubjectsTable.js
  frontend/src/main/utils/UCSBSubjectUtils.js
  frontend/src/stories/components/UCSBSubjects/UCSBSubjectsTable.stories.js
  frontend/src/tests/components/UCSBSubjectsTest/UCSBSubjectsTable.test.js
  frontend/src/tests/utils/UCSBSubjectUtils.test.js
Labels: w22-7pm-2, Merge-Candidate

#32 Implemented menu bar items and page components placeholders for PersonalSchedule
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/PersonalSchedule/PersonalScheduleCreatePage.js
  frontend/src/main/pages/PersonalSchedule/PersonalScheduleEditPage.js
  frontend/src/main/pages/PersonalSchedule/PersonalScheduleIndexPage.js
  frontend/src/stories/pages/HomePage/PersonalSchedule/PersonalScheduleCreatePage.stories.js
  frontend/src/stories/pages/HomePage/PersonalSchedule/PersonalScheduleIndexPage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalScheduleCreatePage.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalScheduleEditPage.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalScheduleIndexPage.test.js
Labels: w22-7pm-2, Merge-Candidate

#31 made Courses Table for lectures Only and fixture and limit the word with description
  frontend/src/fixtures/coursesFixtures.js
  frontend/src/main/components/Courses/CoursesTable.js
  frontend/src/stories/components/Courses/CoursesTable.stories.js
  frontend/src/tests/components/Courses/CoursesTable.test.js
  issues/epic01/21-UCSB-curriculum-service copy.md
Labels: w22-7pm-1, 10

#38 BUGFIX: Load Subjects (from PR #29)
  frontend/src/fixtures/loadsubjectsFixtures.js
  frontend/src/main/pages/LoadSubjectsPage.js
  frontend/src/tests/pages/LoadSubjectsPage.test.js
Labels: w22-7pm-2, 10

#35 Shuya currservice
  src/main/java/edu/ucsb/cs156/example/controllers/UCSBCurriculumController.java
  src/main/java/edu/ucsb/cs156/example/services/UCSBCurriculumService.java
  src/test/java/edu/ucsb/cs156/example/controllers/UCSBCurriculumControllerTests.java
  src/test/java/edu/ucsb/cs156/example/services/UCSBCurriculumServiceTest.java
Labels: w22-7pm-1, 20

#39 Edit page for PersonalSchedule
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/PersonalSchedule/PersonalScheduleTable.js
  frontend/src/main/pages/PersonalSchedule/PersonalScheduleEditPage.js
  frontend/src/main/utils/PersonalScheduleUtils.js
  frontend/src/stories/pages/HomePage/PersonalSchedule/PersonalScheduleEditPage.stories.js
  frontend/src/tests/pages/PersonalSchedule/PersonalScheduleEditPage.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalScheduleCreatePage.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalScheduleEditPage.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalScheduleIndexPage.test.js
  frontend/src/tests/utils/PersonalScheduleUtils.test.js
Labels: w22-7pm-2

#41 Personal Schedule Table Component
  frontend/src/fixtures/personalSchedulesFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/PersonalSchedule/PersonalScheduleTable.js
  frontend/src/main/pages/PersonalSchedule/PersonalScheduleIndexPage.js
  frontend/src/main/utils/PersonalScheduleUtils.js
  frontend/src/stories/components/PersonalSchedule/PersonalScheduleTable.stories.js
  frontend/src/tests/components/PersonalSchedule/PersonalScheduleTable.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalScheduleIndexPage.test.js
  frontend/src/tests/utils/PersonalScheduleUtils.test.js
Labels: w22-7pm-2

#45 Basic search form
  frontend/src/main/components/BasicCourseSearch/BasicCourseSearchForm.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/stories/components/BasicCourseSearch/BasicCourseSearchForm.stories.js
  frontend/src/tests/components/BasicCourseSearch/BasicCourseSearchForm.test.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
Labels: w22-7pm-1, 10

#48 Changing timeout-minutes to 40 from 10
  .github/workflows/02-frontend-01-tests.yml
Labels: w22-7pm-1, 5

#47 Created Basic Course Search Page & Basic List Page & Tests & Storybook
  frontend/src/App.js
  frontend/src/main/components/BasicCourseSearch/BasicCourseSearchForm.js
  frontend/src/main/components/Courses/CoursesTable.js
  frontend/src/main/components/Level/LevelDropdown.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/BasicCourseListPage.js
  frontend/src/main/pages/BasicCourseSearchPage.js
  frontend/src/stories/pages/HomePage/BasicCourseListPage.stories.js
  frontend/src/stories/pages/HomePage/BasicCourseSearchPage.stories.js
  frontend/src/tests/components/BasicCourseSearch/BasicCourseSearchForm.test.js
  frontend/src/tests/components/Level/LevelDropdown.test.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/BasicCourseListPage.test.js
  frontend/src/tests/pages/BasicCourseSearchPage.test.js
  src/main/java/edu/ucsb/cs156/example/controllers/UCSBCurriculumController.java
  src/main/java/edu/ucsb/cs156/example/services/UCSBCurriculumService.java
  src/test/java/edu/ucsb/cs156/example/services/UCSBCurriculumServiceTest.java
Labels: w22-7pm-1, 5, 20

#43 Personal Schedule Form Component
  .github/workflows/02-frontend-03-mutation-testing.yml
  frontend/src/App.js
  frontend/src/main/components/PersonalSchedule/PersonalScheduleForm.js
  frontend/src/main/components/Quarters/SingleQuarterDropdown.js
  frontend/src/main/pages/PersonalSchedule/PersonalScheduleCreatePage.js
  frontend/src/stories/components/PersonalSchedule/PersonalScheduleForm.stories.js
  frontend/src/tests/components/PersonalSchedule/PersonalScheduleForm.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalScheduleCreatePage.test.js
Labels: w22-7pm-2, attn-respond to CR

#44 Edit Form for Schedule Table
  frontend/src/main/components/BasicCourseSearch/BasicCourseSearchForm.js
  frontend/src/main/components/PersonalSchedule/PersonalScheduleForm.js
  frontend/src/main/components/PersonalSchedule/PersonalScheduleTable.js
  frontend/src/main/components/Quarters/SingleQuarterDropdown.js
  frontend/src/main/pages/PersonalSchedule/PersonalScheduleCreatePage.js
  frontend/src/main/pages/PersonalSchedule/PersonalScheduleEditPage.js
  frontend/src/stories/components/BasicCourseSearch/BasicCourseSearchForm.stories.js
  frontend/src/stories/pages/HomePage/PersonalSchedule/PersonalScheduleEditPage.stories.js
  frontend/src/tests/components/BasicCourseSearch/BasicCourseSearchForm.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalScheduleCreatePage.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalScheduleEditPage.test.js
Labels: w22-7pm-2
